### ISSUE TITLE
Prototype find_at_location endpoint

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/loci-integration-api#15]
https://github.com/CSIRO-enviro-informatics/loci-integration-api/tree/find_by_point prototype of limited find by lat lon and generate uri.

**Comment by jyucsiro** [comment]
hooked up with the ui in loci-integration-app and working well.

**Comment by jyucsiro** [comment]
can i close this issue @benjaminleighton ?

**Comment by benjaminleighton** [comment]
Yes
