### ISSUE TITLE
Figure out where to store terraform state for loci-integration-api

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#16]

**Comment by benjaminleighton** [comment]
State is in terraform cloud at terraform.io. Everyone can be added to co manage remote state on aws. It is free for current use. We can migrate back to local disk or other state management systems. It possibly supports namespacing and git push based deployments. Currently things are set to "local" mode which means AWS credentials stay local and the more advanced automatic build features are disabled.
