### ISSUE TITLE
Test to ensure geofabric holes are fixed

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/loci-integration-api#29]
Use new test data in https://github.com/CSIRO-enviro-informatics/loci-testdata/pull/4 to check to see if all specified contracted catchments are in the river region 9400357

**Comment by jyucsiro** [comment]
Test is now defined in loci-testdata. See https://github.com/CSIRO-enviro-informatics/loci-testdata/search?q=9400357&unscoped_q=9400357
