### ISSUE TITLE
add option flags to include/exclude area and proportion in the payload

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#32]
Requirement to add flag to include/exclude area and proportion in /location/overlaps endpoint

**Comment by benjaminleighton** [comment]
This functionality is built into the overlaps endpoint via the "areas" and "proportions" parameters. It was broken when "crosswalk" was specified. At various points in the crosswalk overlaps functionality "area" and "proportion" are required and interact. The current fix post processes the results to exclude/include "areas" and "proportions" based on the parameters. Future work might improve the elegance and efficiency by filtering out area and proportion deeper in the logic and avoiding post processing but this approach works and is probably reasonably performant.

**Comment by jyucsiro** [comment]
i think this is reasonable for now
