### ISSUE TITLE
turn on gnaf dataset in /location/overlaps

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#33]
enable gnaf querying in /location/overlaps

**Comment by benjaminleighton** [comment]
The current overlaps endpoint doesn't do GNAF area based logic. So when areas and/or proportions are specified to be included the logic will return an error indicating areas are unavailable for GNAF. 

The overlaps endpoint with crosswalks enabled reuses the overlaps endpoint logic. In its current implementation it expects to be distributing an area from the specified query "uri" to targets across the related U shape. That is the area is distributed to things within it, things overlapping, and things that contain the overlapping things (the other side of the U). 

Adapting this needs to account for two broad cases. One is when we are asking for the crosswalk overlaps for a GNAF uri. 

Perhaps in this case the logic should:

* Find all children of the GNAF uri in the same spatial hierarchy down to the base address unit
* Ignore any area distribution to the address unit as they are points
* Find base units that "overlap" with the address unit but are in a different spatial hierarchy
* Find parents of the base units in the other hierarchy
* Return results indicating that the specified GNAF URIs overlap with the results list but not include any areas or proportions

The other case is when we are asking for a crosswalk overlap from some object with area e.g an SA2 to a GNAF entity. 

In this case the logic might:

* On encountering a GNAF uri distribute an "unknown" amount of the original area with an "unknown" proportion

I'm not sure but in any case the logic for crosswalks overlaps will need to be carefully modified, probably adding a bunch of conditionals, to deal with this case.

**Comment by benjaminleighton** [comment]
I've implemented half of the functionality that I think is required. crosswalk overlaps queries now will return gnaf hierarchy objects on the "to" side of the query if they overlap with the "from" uri. No amount of overlap is provided. No area for the objects in the gnaf hierarchy are returned. There isn't logic yet to deal with crosswalk overlaps queries from something in the gnaf hierarchy.

**Comment by benjaminleighton** [comment]
for GNAF "from something with no area to things with area and report "nan" for reversePercentage but "100%" for forwardPercentage and set the intersection area to 0"

**Comment by benjaminleighton** [comment]
Probably for point to polygon and other use cases would be good to switch back on isContains / isWithin functionality (like in the non overlaps cache).

**Comment by jyucsiro** [comment]
The functionality has been added and is being used
