### ISSUE TITLE
Bugs in hierarchy_overlap /location/overlaps implementation

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#38]
On the PR #36, found some bugs that the previous version did not have. Should be backwards compatible, where `crosswalks=false`...

**1. Find overlaps for a CC**

This works in `master`:
https://api2.loci.cat/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fgeofabric%2Fcontractedcatchment%2F12101547&areas=true&proportion=true&contains=false&within=false&crosswalk=false&count=1000&offset=0

In the `hierarchy_overlaps`, the same query causes an internal server error (local deployment):
http://localhost:8080/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fgeofabric%2Fcontractedcatchment%2F12101547&areas=true&proportion=true&contains=false&within=false&crosswalk=false&count=1000&offset=0

**2. Find overlaps incl. wholly contained for a CC**

In the `master` branch, this works (i.e. `contains=true`):
https://api2.loci.cat/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fgeofabric%2Fcontractedcatchment%2F12101547&areas=true&proportion=true&contains=true&within=false&count=1000&offset=0

In the `hierarchy_overlaps`, the same query causes an internal server error (local deployment):
http://localhost:8080/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fgeofabric%2Fcontractedcatchment%2F12101547&areas=true&proportion=true&contains=true&within=false&count=1000&offset=0

**3. Find overlaps incl. features that a CC is within**

In the `master` branch, this works (i.e. `within=true`):
https://api2.loci.cat/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fgeofabric%2Fcontractedcatchment%2F12101547&areas=true&proportion=true&contains=false&within=true&count=1000&offset=0

In the `hierarchy_overlaps`, the same query causes an internal server error (local deployment):
http://localhost:8080/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fgeofabric%2Fcontractedcatchment%2F12101547&areas=true&proportion=true&contains=false&within=true&count=1000&offset=0

**Comment by benjaminleighton** [comment]
Fixed
