### ISSUE TITLE
DGGS engine powered find-at-point API

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#76]

**Comment by bellie888** [comment]
There is a DGGS enablement script example on Git (Auspix engine) which will produce the DGGS equivalent of a point. The point will be somewhere within the cell, not necessarily in the centre. Choice of resolution is important to suit the workflow being used.

**Comment by jyucsiro** [comment]
won't do this in the loci-integration-api
