### ISSUE TITLE
DGGS engine powered find-at-polygon API

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#77]
Design and prototype an online Web API that accepts input and outputs

Input:
* Single polygon (e.g. geojson, wkt)
* Format (geojson, wkt)
* Projection (default WGS84)

**Comment by bellie888** [comment]
There is a DGGS enablement script example on Git which will produce the DGGS equivalent of a polygon. It will input a shapefile and generate a csv or shapefile output that has one line for each cell. Many DGGS cells will be used to represent one polygon. Data from the source shapefile can be included in the output. Later, when integrating data based on DGGS cell, the data from the two sources are brought together on the cell.

**Comment by jyucsiro** [comment]
won't do this in the loci-integration-api
