### ISSUE TITLE
DGGS engine powered find-at-line API

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#78]

**Comment by bellie888** [comment]
There is a DGGS enablement script example on Git (Auspix engine) which will produce the DGGS equivalent of a line. It does this by looking at all the points the line is made of, and for each point calculating the DGGS cell it is in. The DGGS resolution must be chosen as well. If the line has few points, it may need to to be "densified"  in GIS first. The script filters out duplicate cells as it runs - ie when two points are inside the one cell. Selection of the resolution involves many factors, and will produce a variety of usable results depending on the problem to solved.

**Comment by jyucsiro** [comment]
won't do this in the loci-integration-api
